'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase/client'
import { useAuthStore } from '@/lib/store/useAuthStore'
import toast from 'react-hot-toast'

interface Prescription {
  id: string
  prescription_date: string
  diagnosis: string
  notes: string
  follow_up_date: string
  doctor: {
    id: string
    speciality: string
    profile: {
      name: string
    }
  }
  medicines: Medicine[]
}

interface Medicine {
  id: string
  name: string
  dosage: string
  duration: string
  timing: string
  instructions: string
}

export default function PrescriptionsPage() {
  const { profile } = useAuthStore()
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedPrescription, setSelectedPrescription] = useState<Prescription | null>(null)

  // Fetch prescriptions - without useCallback
  useEffect(() => {
    const fetchPrescriptions = async () => {
      if (!profile?.id) {
        setLoading(false)
        return
      }

      try {
        // First fetch prescriptions
        const { data: prescriptionsData, error: prescriptionsError } = await supabase
          .from('prescriptions')
          .select(`
            *,
            doctor:doctors(
              id,
              speciality,
              profile:profiles(name)
            )
          `)
          .eq('patient_id', profile.id)
          .order('prescription_date', { ascending: false })

        if (prescriptionsError) throw prescriptionsError

        if (!prescriptionsData || prescriptionsData.length === 0) {
          setPrescriptions([])
          setLoading(false)
          return
        }

        // Fetch medicines for each prescription
        const prescriptionIds = prescriptionsData.map(p => p.id)
        const { data: medicinesData, error: medicinesError } = await supabase
          .from('prescription_medicines')
          .select('*')
          .in('prescription_id', prescriptionIds)

        if (medicinesError) throw medicinesError

        // Group medicines by prescription_id
        const medicinesByPrescription = new Map()
        medicinesData?.forEach(med => {
          if (!medicinesByPrescription.has(med.prescription_id)) {
            medicinesByPrescription.set(med.prescription_id, [])
          }
          medicinesByPrescription.get(med.prescription_id).push(med)
        })

        // Merge prescriptions with their medicines
        const mergedPrescriptions: Prescription[] = prescriptionsData.map(pres => ({
          ...pres,
          medicines: medicinesByPrescription.get(pres.id) || []
        }))

        setPrescriptions(mergedPrescriptions)
      } catch (error) {
        console.error('Error fetching prescriptions:', error)
        toast.error('Failed to load prescriptions')
      } finally {
        setLoading(false)
      }
    }

    fetchPrescriptions()
  }, [profile?.id])

  const downloadPrescription = (prescription: Prescription) => {
    // Generate PDF or text content
    const content = `
      QUICK TREAT - PRESCRIPTION
      ===========================
      
      Patient Name: ${profile?.name}
      Date: ${new Date(prescription.prescription_date).toLocaleDateString()}
      Doctor: ${prescription.doctor?.profile?.name}
      Speciality: ${prescription.doctor?.speciality}
      
      Diagnosis: ${prescription.diagnosis}
      
      Medicines:
      ${prescription.medicines.map(med => 
        `- ${med.name}: ${med.dosage} - ${med.duration} (${med.timing})
         Instructions: ${med.instructions}`
      ).join('\n')}
      
      Notes: ${prescription.notes}
      Follow-up Date: ${prescription.follow_up_date ? new Date(prescription.follow_up_date).toLocaleDateString() : 'N/A'}
      
      Generated by Quick Treat
    `

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `prescription_${prescription.id.slice(0, 8)}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Prescription downloaded')
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    )
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <h1 className="text-3xl font-bold text-text-dark mb-8">My Prescriptions</h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Prescriptions List */}
        <div className="lg:col-span-1 space-y-4">
          {prescriptions.map((pres) => (
            <div
              key={pres.id}
              onClick={() => setSelectedPrescription(pres)}
              className={`bg-white rounded-2xl border p-4 cursor-pointer transition hover:shadow-md ${
                selectedPrescription?.id === pres.id
                  ? 'border-primary bg-primary-light/10'
                  : 'border-border'
              }`}
            >
              <div className="flex justify-between items-start">
                <div>
                  <p className="font-semibold text-teal-dark">{pres.doctor?.profile?.name}</p>
                  <p className="text-sm text-text-grey">{pres.doctor?.speciality}</p>
                  <p className="text-xs text-text-grey mt-1">
                    {new Date(pres.prescription_date).toLocaleDateString()}
                  </p>
                </div>
                <span className="text-xs px-2 py-1 bg-green-100 text-green-700 rounded-full">
                  {pres.medicines.length} medicines
                </span>
              </div>
            </div>
          ))}

          {prescriptions.length === 0 && (
            <div className="bg-white rounded-2xl border border-border p-8 text-center">
              <p className="text-text-grey">No prescriptions found</p>
            </div>
          )}
        </div>

        {/* Prescription Details */}
        <div className="lg:col-span-2">
          {selectedPrescription ? (
            <div className="bg-white rounded-2xl border border-border overflow-hidden">
              <div className="p-6 border-b border-border bg-gray-50">
                <div className="flex justify-between items-start">
                  <div>
                    <h2 className="text-xl font-semibold text-teal-dark">Prescription Details</h2>
                    <p className="text-sm text-text-grey mt-1">
                      Prescribed by Dr. {selectedPrescription.doctor?.profile?.name}
                    </p>
                  </div>
                  <button
                    onClick={() => downloadPrescription(selectedPrescription)}
                    className="px-4 py-2 bg-primary text-white rounded-lg text-sm hover:bg-primary-dark"
                  >
                    Download
                  </button>
                </div>
              </div>

              <div className="p-6 space-y-6">
                {/* Diagnosis */}
                <div>
                  <h3 className="font-semibold text-teal-dark mb-2">Diagnosis</h3>
                  <p className="text-text-grey">{selectedPrescription.diagnosis}</p>
                </div>

                {/* Medicines */}
                <div>
                  <h3 className="font-semibold text-teal-dark mb-3">Medicines</h3>
                  <div className="space-y-3">
                    {selectedPrescription.medicines.map((med) => (
                      <div key={med.id} className="border border-border rounded-xl p-4">
                        <div className="flex justify-between items-start">
                          <div>
                            <p className="font-medium text-text-dark">{med.name}</p>
                            <p className="text-sm text-text-grey">Dosage: {med.dosage}</p>
                            <p className="text-sm text-text-grey">Duration: {med.duration}</p>
                            <p className="text-sm text-text-grey">Timing: {med.timing}</p>
                          </div>
                        </div>
                        {med.instructions && (
                          <p className="text-sm text-primary mt-2">📝 {med.instructions}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Notes */}
                {selectedPrescription.notes && (
                  <div>
                    <h3 className="font-semibold text-teal-dark mb-2">Additional Notes</h3>
                    <p className="text-text-grey">{selectedPrescription.notes}</p>
                  </div>
                )}

                {/* Follow-up */}
                {selectedPrescription.follow_up_date && (
                  <div className="bg-yellow-50 rounded-xl p-4">
                    <p className="text-sm text-yellow-700">
                      ⏰ Follow-up Date: {new Date(selectedPrescription.follow_up_date).toLocaleDateString()}
                    </p>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-2xl border border-border p-12 text-center">
              <p className="text-text-grey">Select a prescription to view details</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}